### ISSUE TITLE
Update dataset 24/03/2020

### ISSUE THREAD

**Issue by m-kruth** [2kruman/COVID19-NZ-known-cases#23]
Update the dataset with 24/03/2020 changes

**Comment by m-kruth** [comment]
Do you want to take a shot at this one @RapidCompiler?

**Comment by m-kruth** [comment]
Also do you have a Kaggle account? I will add you as a collaborator on the dataset so that you can push updates from this repository to the dataset.

**Comment by m-kruth** [comment]
FYI the _current cases_ page is currently down. I've found that the MOH tend to do this when they have announced new cases but have not yet updated the table. My guess would be that they take down the page while they catch up on inputting details into the table.

**Comment by RapidCompiler** [comment]
> Also do you have a Kaggle account? I will add you as a collaborator on the dataset so that you can push updates from this repository to the dataset.

Yes, I do have a kaggle account. My username is "datamonger19".

**Comment by RapidCompiler** [comment]
> FYI the _current cases_ page is currently down. I've found that the MOH tend to do this when they have announced new cases but have not yet updated the table. My guess would be that they take down the page while they catch up on inputting details into the table.

That is the only explanation. Nvmd. I've self-assigned this. I'll take care of the updation. You get some rest on the other side of the world ; )

**Comment by RapidCompiler** [comment]
I've solved this issue with merge numbered #31.
