### ISSUE TITLE
Put flights into a python list

### ISSUE THREAD

**Issue by m-kruth** [2kruman/COVID19-NZ-known-cases#3]
- The field containing the list of flights numbers is currently stored in the following format:
```AA83, NZ828```
- Selecting one of these cells with pandas results in a single string containing all flight numbers:
```
df['Flight Numbers'][9]
'AA83, NZ828'
```
- If they are put in square brackets, each cell would be read as a python list by pandas. The benefit to the user would be that they would not need to perform string operations to extract flight numbers.

**Comment by 2kruman** [comment]
- The field containing the list of flights numbers is currently stored in the following format:
AA83, NZ828
- Selecting one of these cells with pandas results in a single string containing all flight numbers:
```
df['Flight Numbers'][9]
'AA83, NZ828'
```
- If they are put in square brackets, each cell would be read as a python list by pandas. The benefit to the user would be that they would not need to perform string operations to extract flight numbers.

**Comment by RapidCompiler** [comment]
No worries. I am new to GitHub. I see you are too. Would you like to collaborate to make projects, raise and merge issues and so on?
